spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      # Managed routes
      routes[0]:
        id: shopping-cart-app
        uri: lb://SHOPPING-CART-APP
        predicates[0]: Path=/cart/**, /products/**

      routes[1]:
        id: users-app
        uri: lb://USERS-APP
        predicates[0]: Path=/user/**

      #default-filters: TokenRelay

    loadbalancer:
      ribbon:
        enabled: false


# Eureka client configuration
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

  client:
    serviceUrl:
      defaultZone: http://${EUREKA_IP}:${EUREKA_PORT}/eureka/

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    org:
      springframework:
        security: DEBUG
