spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      # Managed routes
      routes:
        - id: shopping-cart-app
          uri: lb://SHOPPING-CART-APP
          predicates:
            - Path=/cart/**, /products/**

        - id: users-app
          uri: lb://USERS-APP
          predicates:
            - Path=/user/**

      default-filters: TokenRelay

    loadbalancer:
      ribbon:
        enabled: false

    security:
      oauth2:

        # Authorization server location
        resourceserver:
          jwt:
            issuer-uri: http://${AUTHSERVER_IP}:${AUTHSERVER_PORT}/realms/digitar120-shopping-cart-project-realm

        client:
          provider:
            keycloak:
              issuer-uri: http://${AUTHSERVER_IP}:${AUTHSERVER_PORT}/realms/digitar120-shopping-cart-project-realm

  # Eureka client configuration
  eureka:
    instance:
      instance-id: ${spring.application.name}:${random.uuid}
      prefer-ip-address: true

    client:
      serviceUrl:
        defaultZone: http://${EUREKA_IP}:${EUREKA_PORT}/eureka/

    output:
      ansi:
        enabled: ALWAYS

  logging:
    level:
      org:
        springframework:
          security: DEBUG