usersapp:
  property: Shopping Cart App Development Configuration

server:
  port: ${APPPORT}

users-service-ip: ${USERS_IP}
users-service-port: ${USERS_PORT}

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

#hibernate: DEBUG

spring:
  output:
    ansi:
      enabled: ALWAYS

  application:
    name: shopping-cart-app

  datasource:
    driver-class-name: org.h2.Driver
    username: a
    password: a
    url: "jdbc:h2:mem:shoppingcartapp;DB_CLOSE_ON_EXIT=false"

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none

  rabbitmq:
    host: ${RABBITMQ_IP}
    port: ${RABBITMQ_PORT}
    username: guest
    password: guest

  # Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${AUTHSERVER_IP}:${AUTHSERVER_PORT}/realms/digitar120-shopping-cart-project-realm

      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: spring-cloud-openfeign-feignclient
            client-secret: zGtbAcOLGAwDJQ17k2kv080KsLLXFy2u


        provider:
          keycloak:
            token-uri: http://${AUTHSERVER_IP}:${AUTHSERVER_PORT}/realms/digitar120-shopping-cart-project-realm/protocol/openid-connect/token
            authorization-uri: http://${AUTHSERVER_IP}:${AUTHSERVER_PORT}/realms/master/protocol/openid-connect/auth

  cloud:
    openfeign:
      oauth2:
        enabled: true

      circuitbreaker:
        enabled: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

  client:
    serviceUrl:
      defaultZone: http://${EUREKA_IP}:${EUREKA_PORT}/eureka/

feign:
  circuitbreaker:
    enabled: true

#management:
#  endpoints:
#    web:
#      exposure:
        #include: "*"
