usersapp:
  property: Users App Development Configuration

server:
  port: 9001

spring:
  output:
    ansi:
      enabled: ALWAYS

  application:
    name: users-app

  datasource:
    driver-class-name: org.h2.Driver
    username: a
    password: a
    url: "jdbc:h2:mem:usersapp;DB_CLOSE_ON_EXIT=false;NON_KEYWORDS=user"
      # Workaround. El servicio trata con una tabla SQL llamada "USER" que es palabra reservada de H2 (¿o SQL?). Se
      # pueden prevenir errores en los archivos schema y data, pero no en las sentencias hechas por JPA.Próximos
    # microservicios tendrán una tabla de usuarios con otro nombre.

    initialization-mode: always
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none

  rabbitmq:
    host: ${RABBITMQ_IP}
    port: ${RABBITMQ_PORT}
      # 5672
    username: guest
    password: guest

  sql:
    init:
      mode: always

  # Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${AUTHSERVER_IP}:${AUTHSERVER_PORT}/realms/digitar120-shopping-cart-project-realm
          # 9090

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

  client:
    serviceUrl:
      defaultZone: http://${EUREKA_IP}:${EUREKA_PORT}/eureka/

management:
  endpoint:
    web:
      exposure:
        include: "*"